# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\00085-PROGRAMMING & CODING PROJECTS\Python Programming\190422_python tutorial - programming with Mosh\PROMFI 2\Promfi_2.0_UI.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!
# import sys
# from PyQt5.QtCore import pyqtSlot
# from PyQt5.QtWidgets import QApplication, QDialog
# from PyQt5.uic import loadUi
from PyQt5 import QtCore, QtGui, QtWidgets
# import os
# import openpyxl as xl

class Ui_promfi_dialog(object):
    def setupUi(self, promfi_dialog):
        promfi_dialog.setObjectName("promfi_dialog")
        promfi_dialog.resize(974, 155)
        self.buttonBox = QtWidgets.QDialogButtonBox(promfi_dialog)
        self.buttonBox.setGeometry(QtCore.QRect(620, 70, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox = QtWidgets.QGroupBox(promfi_dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 391, 51))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(210, 20, 16, 21))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setIndent(0)
        self.label.setObjectName("label")
        self.comboBox_14 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_14.setGeometry(QtCore.QRect(10, 20, 41, 22))
        self.comboBox_14.setEditable(True)
        self.comboBox_14.setMaxVisibleItems(10)
        self.comboBox_14.setObjectName("comboBox_14")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_15 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_15.setGeometry(QtCore.QRect(50, 20, 41, 22))
        self.comboBox_15.setEditable(True)
        self.comboBox_15.setMaxVisibleItems(10)
        self.comboBox_15.setObjectName("comboBox_15")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_16 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_16.setGeometry(QtCore.QRect(90, 20, 41, 22))
        self.comboBox_16.setEditable(True)
        self.comboBox_16.setMaxVisibleItems(10)
        self.comboBox_16.setObjectName("comboBox_16")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_17 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_17.setGeometry(QtCore.QRect(130, 20, 41, 22))
        self.comboBox_17.setEditable(True)
        self.comboBox_17.setMaxVisibleItems(10)
        self.comboBox_17.setObjectName("comboBox_17")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_18 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_18.setGeometry(QtCore.QRect(170, 20, 41, 22))
        self.comboBox_18.setEditable(True)
        self.comboBox_18.setMaxVisibleItems(10)
        self.comboBox_18.setObjectName("comboBox_18")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_19 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_19.setGeometry(QtCore.QRect(220, 20, 41, 22))
        self.comboBox_19.setEditable(True)
        self.comboBox_19.setMaxVisibleItems(10)
        self.comboBox_19.setObjectName("comboBox_19")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_19.addItem("")
        self.comboBox_20 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_20.setGeometry(QtCore.QRect(260, 20, 41, 22))
        self.comboBox_20.setEditable(True)
        self.comboBox_20.setMaxVisibleItems(10)
        self.comboBox_20.setObjectName("comboBox_20")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_20.addItem("")
        self.comboBox_21 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_21.setGeometry(QtCore.QRect(300, 20, 41, 22))
        self.comboBox_21.setEditable(True)
        self.comboBox_21.setMaxVisibleItems(10)
        self.comboBox_21.setObjectName("comboBox_21")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.comboBox_22 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_22.setGeometry(QtCore.QRect(340, 20, 41, 22))
        self.comboBox_22.setEditable(True)
        self.comboBox_22.setMaxVisibleItems(10)
        self.comboBox_22.setObjectName("comboBox_22")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.comboBox_22.addItem("")
        self.groupBox_2 = QtWidgets.QGroupBox(promfi_dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(640, 10, 321, 51))
        self.groupBox_2.setObjectName("groupBox_2")
        self.comboBox_6 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_6.setGeometry(QtCore.QRect(270, 20, 41, 22))
        self.comboBox_6.setEditable(True)
        self.comboBox_6.setMaxVisibleItems(10)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_5 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_5.setGeometry(QtCore.QRect(210, 20, 41, 22))
        self.comboBox_5.setEditable(True)
        self.comboBox_5.setMaxVisibleItems(10)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(250, 20, 16, 21))
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setIndent(0)
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(130, 20, 16, 21))
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setIndent(0)
        self.label_2.setObjectName("label_2")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_2.setGeometry(QtCore.QRect(50, 20, 41, 22))
        self.comboBox_2.setEditable(True)
        self.comboBox_2.setMaxVisibleItems(10)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(190, 20, 16, 21))
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setIndent(0)
        self.label_3.setObjectName("label_3")
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_3.setGeometry(QtCore.QRect(90, 20, 41, 22))
        self.comboBox_3.setEditable(True)
        self.comboBox_3.setMaxVisibleItems(10)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_4.setGeometry(QtCore.QRect(150, 20, 41, 22))
        self.comboBox_4.setEditable(True)
        self.comboBox_4.setMaxVisibleItems(10)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox.setGeometry(QtCore.QRect(10, 20, 41, 22))
        self.comboBox.setEditable(True)
        self.comboBox.setMaxVisibleItems(10)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.groupBox_3 = QtWidgets.QGroupBox(promfi_dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(430, 10, 201, 51))
        self.groupBox_3.setObjectName("groupBox_3")
        self.comboBox_9 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_9.setGeometry(QtCore.QRect(50, 20, 41, 22))
        self.comboBox_9.setEditable(True)
        self.comboBox_9.setMaxVisibleItems(10)
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(90, 20, 16, 21))
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setIndent(0)
        self.label_7.setObjectName("label_7")
        self.comboBox_12 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_12.setGeometry(QtCore.QRect(10, 20, 41, 22))
        self.comboBox_12.setEditable(True)
        self.comboBox_12.setMaxVisibleItems(10)
        self.comboBox_12.setObjectName("comboBox_12")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_10 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_10.setGeometry(QtCore.QRect(150, 20, 41, 22))
        self.comboBox_10.setEditable(True)
        self.comboBox_10.setMaxVisibleItems(10)
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_13 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_13.setGeometry(QtCore.QRect(110, 20, 41, 22))
        self.comboBox_13.setEditable(True)
        self.comboBox_13.setMaxVisibleItems(10)
        self.comboBox_13.setObjectName("comboBox_13")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.label_8 = QtWidgets.QLabel(promfi_dialog)
        self.label_8.setGeometry(QtCore.QRect(410, 30, 16, 21))
        self.label_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setIndent(0)
        self.label_8.setObjectName("label_8")
        self.pushButton = QtWidgets.QPushButton(promfi_dialog)
        self.pushButton.setGeometry(QtCore.QRect(10, 70, 131, 28))
        self.pushButton.setObjectName("pushButton")
        self.textEdit = QtWidgets.QTextEdit(promfi_dialog)
        self.textEdit.setGeometry(QtCore.QRect(150, 70, 611, 31))
        self.textEdit.setObjectName("textEdit")
        # self.pushButton_2 = QtWidgets.QPushButton(promfi_dialog)
        # self.pushButton_2.setGeometry(QtCore.QRect(10, 100, 131, 28))
        # self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(promfi_dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 100, 131, 28))
        self.pushButton_3.setObjectName("pushButton")

        self.retranslateUi(promfi_dialog)
        self.buttonBox.accepted.connect(promfi_dialog.accept)
        self.buttonBox.rejected.connect(promfi_dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(promfi_dialog)

        self.pushButton.clicked.connect(self.takeText)
        self.pushButton_3.clicked.connect(self.soflo())
        # self.pushButton_2.clicked.connect(self.task_code())
        # self.pushButton_2.clicked.connect(self.storeText())
        # self.textEdit.clicked.connect(self.takeTextEE)
        # self.pushButton.clicked.connect(self.print_message)

    def retranslateUi(self, promfi_dialog):
        _translate = QtCore.QCoreApplication.translate
        promfi_dialog.setWindowTitle(_translate("promfi_dialog", "Promfi 2.0"))
        self.groupBox.setTitle(_translate("promfi_dialog", "Project-Resource Number Generator"))
        self.label.setText(_translate("promfi_dialog", "-"))
        self.comboBox_14.setItemText(0, _translate("promfi_dialog", "0"))
        self.comboBox_14.setItemText(1, _translate("promfi_dialog", "1"))
        self.comboBox_14.setItemText(2, _translate("promfi_dialog", "2"))
        self.comboBox_14.setItemText(3, _translate("promfi_dialog", "3"))
        self.comboBox_14.setItemText(4, _translate("promfi_dialog", "4"))
        self.comboBox_14.setItemText(5, _translate("promfi_dialog", "5"))
        self.comboBox_14.setItemText(6, _translate("promfi_dialog", "6"))
        self.comboBox_14.setItemText(7, _translate("promfi_dialog", "7"))
        self.comboBox_14.setItemText(8, _translate("promfi_dialog", "8"))
        self.comboBox_14.setItemText(9, _translate("promfi_dialog", "9"))
        self.comboBox_15.setItemText(0, _translate("promfi_dialog", "0"))
        self.comboBox_15.setItemText(1, _translate("promfi_dialog", "1"))
        self.comboBox_15.setItemText(2, _translate("promfi_dialog", "2"))
        self.comboBox_15.setItemText(3, _translate("promfi_dialog", "3"))
        self.comboBox_15.setItemText(4, _translate("promfi_dialog", "4"))
        self.comboBox_15.setItemText(5, _translate("promfi_dialog", "5"))
        self.comboBox_15.setItemText(6, _translate("promfi_dialog", "6"))
        self.comboBox_15.setItemText(7, _translate("promfi_dialog", "7"))
        self.comboBox_15.setItemText(8, _translate("promfi_dialog", "8"))
        self.comboBox_15.setItemText(9, _translate("promfi_dialog", "9"))
        self.comboBox_16.setItemText(0, _translate("promfi_dialog", "0"))
        self.comboBox_16.setItemText(1, _translate("promfi_dialog", "1"))
        self.comboBox_16.setItemText(2, _translate("promfi_dialog", "2"))
        self.comboBox_16.setItemText(3, _translate("promfi_dialog", "3"))
        self.comboBox_16.setItemText(4, _translate("promfi_dialog", "4"))
        self.comboBox_16.setItemText(5, _translate("promfi_dialog", "5"))
        self.comboBox_16.setItemText(6, _translate("promfi_dialog", "6"))
        self.comboBox_16.setItemText(7, _translate("promfi_dialog", "7"))
        self.comboBox_16.setItemText(8, _translate("promfi_dialog", "8"))
        self.comboBox_16.setItemText(9, _translate("promfi_dialog", "9"))
        self.comboBox_17.setItemText(0, _translate("promfi_dialog", "0"))
        self.comboBox_17.setItemText(1, _translate("promfi_dialog", "1"))
        self.comboBox_17.setItemText(2, _translate("promfi_dialog", "2"))
        self.comboBox_17.setItemText(3, _translate("promfi_dialog", "3"))
        self.comboBox_17.setItemText(4, _translate("promfi_dialog", "4"))
        self.comboBox_17.setItemText(5, _translate("promfi_dialog", "5"))
        self.comboBox_17.setItemText(6, _translate("promfi_dialog", "6"))
        self.comboBox_17.setItemText(7, _translate("promfi_dialog", "7"))
        self.comboBox_17.setItemText(8, _translate("promfi_dialog", "8"))
        self.comboBox_17.setItemText(9, _translate("promfi_dialog", "9"))
        self.comboBox_18.setItemText(0, _translate("promfi_dialog", "0"))
        self.comboBox_18.setItemText(1, _translate("promfi_dialog", "1"))
        self.comboBox_18.setItemText(2, _translate("promfi_dialog", "2"))
        self.comboBox_18.setItemText(3, _translate("promfi_dialog", "3"))
        self.comboBox_18.setItemText(4, _translate("promfi_dialog", "4"))
        self.comboBox_18.setItemText(5, _translate("promfi_dialog", "5"))
        self.comboBox_18.setItemText(6, _translate("promfi_dialog", "6"))
        self.comboBox_18.setItemText(7, _translate("promfi_dialog", "7"))
        self.comboBox_18.setItemText(8, _translate("promfi_dialog", "8"))
        self.comboBox_18.setItemText(9, _translate("promfi_dialog", "9"))
        self.comboBox_19.setItemText(0, _translate("promfi_dialog", "0"))
        self.comboBox_19.setItemText(1, _translate("promfi_dialog", "1"))
        self.comboBox_19.setItemText(2, _translate("promfi_dialog", "2"))
        self.comboBox_19.setItemText(3, _translate("promfi_dialog", "3"))
        self.comboBox_19.setItemText(4, _translate("promfi_dialog", "4"))
        self.comboBox_19.setItemText(5, _translate("promfi_dialog", "5"))
        self.comboBox_19.setItemText(6, _translate("promfi_dialog", "6"))
        self.comboBox_19.setItemText(7, _translate("promfi_dialog", "7"))
        self.comboBox_19.setItemText(8, _translate("promfi_dialog", "8"))
        self.comboBox_19.setItemText(9, _translate("promfi_dialog", "9"))
        self.comboBox_20.setItemText(0, _translate("promfi_dialog", "0"))
        self.comboBox_20.setItemText(1, _translate("promfi_dialog", "1"))
        self.comboBox_20.setItemText(2, _translate("promfi_dialog", "2"))
        self.comboBox_20.setItemText(3, _translate("promfi_dialog", "3"))
        self.comboBox_20.setItemText(4, _translate("promfi_dialog", "4"))
        self.comboBox_20.setItemText(5, _translate("promfi_dialog", "5"))
        self.comboBox_20.setItemText(6, _translate("promfi_dialog", "6"))
        self.comboBox_20.setItemText(7, _translate("promfi_dialog", "7"))
        self.comboBox_20.setItemText(8, _translate("promfi_dialog", "8"))
        self.comboBox_20.setItemText(9, _translate("promfi_dialog", "9"))
        self.comboBox_21.setItemText(0, _translate("promfi_dialog", "0"))
        self.comboBox_21.setItemText(1, _translate("promfi_dialog", "1"))
        self.comboBox_21.setItemText(2, _translate("promfi_dialog", "2"))
        self.comboBox_21.setItemText(3, _translate("promfi_dialog", "3"))
        self.comboBox_21.setItemText(4, _translate("promfi_dialog", "4"))
        self.comboBox_21.setItemText(5, _translate("promfi_dialog", "5"))
        self.comboBox_21.setItemText(6, _translate("promfi_dialog", "6"))
        self.comboBox_21.setItemText(7, _translate("promfi_dialog", "7"))
        self.comboBox_21.setItemText(8, _translate("promfi_dialog", "8"))
        self.comboBox_21.setItemText(9, _translate("promfi_dialog", "9"))
        self.comboBox_22.setItemText(0, _translate("promfi_dialog", "0"))
        self.comboBox_22.setItemText(1, _translate("promfi_dialog", "1"))
        self.comboBox_22.setItemText(2, _translate("promfi_dialog", "2"))
        self.comboBox_22.setItemText(3, _translate("promfi_dialog", "3"))
        self.comboBox_22.setItemText(4, _translate("promfi_dialog", "4"))
        self.comboBox_22.setItemText(5, _translate("promfi_dialog", "5"))
        self.comboBox_22.setItemText(6, _translate("promfi_dialog", "6"))
        self.comboBox_22.setItemText(7, _translate("promfi_dialog", "7"))
        self.comboBox_22.setItemText(8, _translate("promfi_dialog", "8"))
        self.comboBox_22.setItemText(9, _translate("promfi_dialog", "9"))
        self.groupBox_2.setTitle(_translate("promfi_dialog", "Relationship Code"))
        self.comboBox_6.setItemText(0, _translate("promfi_dialog", "a"))
        self.comboBox_6.setItemText(1, _translate("promfi_dialog", "b"))
        self.comboBox_6.setItemText(2, _translate("promfi_dialog", "c"))
        self.comboBox_6.setItemText(3, _translate("promfi_dialog", "d"))
        self.comboBox_6.setItemText(4, _translate("promfi_dialog", "e"))
        self.comboBox_6.setItemText(5, _translate("promfi_dialog", "f"))
        self.comboBox_6.setItemText(6, _translate("promfi_dialog", "g"))
        self.comboBox_6.setItemText(7, _translate("promfi_dialog", "h"))
        self.comboBox_6.setItemText(8, _translate("promfi_dialog", "i"))
        self.comboBox_6.setItemText(9, _translate("promfi_dialog", "j"))
        self.comboBox_6.setItemText(10, _translate("promfi_dialog", "k"))
        self.comboBox_6.setItemText(11, _translate("promfi_dialog", "l"))
        self.comboBox_6.setItemText(12, _translate("promfi_dialog", "m"))
        self.comboBox_6.setItemText(13, _translate("promfi_dialog", "n"))
        self.comboBox_6.setItemText(14, _translate("promfi_dialog", "o"))
        self.comboBox_6.setItemText(15, _translate("promfi_dialog", "p"))
        self.comboBox_6.setItemText(16, _translate("promfi_dialog", "q"))
        self.comboBox_6.setItemText(17, _translate("promfi_dialog", "r"))
        self.comboBox_6.setItemText(18, _translate("promfi_dialog", "s"))
        self.comboBox_6.setItemText(19, _translate("promfi_dialog", "t"))
        self.comboBox_6.setItemText(20, _translate("promfi_dialog", "u"))
        self.comboBox_6.setItemText(21, _translate("promfi_dialog", "v"))
        self.comboBox_6.setItemText(22, _translate("promfi_dialog", "w"))
        self.comboBox_6.setItemText(23, _translate("promfi_dialog", "x"))
        self.comboBox_6.setItemText(24, _translate("promfi_dialog", "y"))
        self.comboBox_6.setItemText(25, _translate("promfi_dialog", "z"))
        self.comboBox_6.setItemText(26, _translate("promfi_dialog", "A"))
        self.comboBox_6.setItemText(27, _translate("promfi_dialog", "B"))
        self.comboBox_6.setItemText(28, _translate("promfi_dialog", "C"))
        self.comboBox_6.setItemText(29, _translate("promfi_dialog", "D"))
        self.comboBox_6.setItemText(30, _translate("promfi_dialog", "E"))
        self.comboBox_6.setItemText(31, _translate("promfi_dialog", "F"))
        self.comboBox_6.setItemText(32, _translate("promfi_dialog", "G"))
        self.comboBox_6.setItemText(33, _translate("promfi_dialog", "H"))
        self.comboBox_6.setItemText(34, _translate("promfi_dialog", "I"))
        self.comboBox_6.setItemText(35, _translate("promfi_dialog", "J"))
        self.comboBox_6.setItemText(36, _translate("promfi_dialog", "K"))
        self.comboBox_6.setItemText(37, _translate("promfi_dialog", "L"))
        self.comboBox_6.setItemText(38, _translate("promfi_dialog", "M"))
        self.comboBox_6.setItemText(39, _translate("promfi_dialog", "N"))
        self.comboBox_6.setItemText(40, _translate("promfi_dialog", "O"))
        self.comboBox_6.setItemText(41, _translate("promfi_dialog", "P"))
        self.comboBox_6.setItemText(42, _translate("promfi_dialog", "Q"))
        self.comboBox_6.setItemText(43, _translate("promfi_dialog", "R"))
        self.comboBox_6.setItemText(44, _translate("promfi_dialog", "S"))
        self.comboBox_6.setItemText(45, _translate("promfi_dialog", "T"))
        self.comboBox_6.setItemText(46, _translate("promfi_dialog", "U"))
        self.comboBox_6.setItemText(47, _translate("promfi_dialog", "V"))
        self.comboBox_6.setItemText(48, _translate("promfi_dialog", "W"))
        self.comboBox_6.setItemText(49, _translate("promfi_dialog", "X"))
        self.comboBox_6.setItemText(50, _translate("promfi_dialog", "Y"))
        self.comboBox_6.setItemText(51, _translate("promfi_dialog", "Z"))
        self.comboBox_5.setItemText(0, _translate("promfi_dialog", "a"))
        self.comboBox_5.setItemText(1, _translate("promfi_dialog", "b"))
        self.comboBox_5.setItemText(2, _translate("promfi_dialog", "c"))
        self.comboBox_5.setItemText(3, _translate("promfi_dialog", "d"))
        self.comboBox_5.setItemText(4, _translate("promfi_dialog", "e"))
        self.comboBox_5.setItemText(5, _translate("promfi_dialog", "f"))
        self.comboBox_5.setItemText(6, _translate("promfi_dialog", "g"))
        self.comboBox_5.setItemText(7, _translate("promfi_dialog", "h"))
        self.comboBox_5.setItemText(8, _translate("promfi_dialog", "i"))
        self.comboBox_5.setItemText(9, _translate("promfi_dialog", "j"))
        self.comboBox_5.setItemText(10, _translate("promfi_dialog", "k"))
        self.comboBox_5.setItemText(11, _translate("promfi_dialog", "l"))
        self.comboBox_5.setItemText(12, _translate("promfi_dialog", "m"))
        self.comboBox_5.setItemText(13, _translate("promfi_dialog", "n"))
        self.comboBox_5.setItemText(14, _translate("promfi_dialog", "o"))
        self.comboBox_5.setItemText(15, _translate("promfi_dialog", "p"))
        self.comboBox_5.setItemText(16, _translate("promfi_dialog", "q"))
        self.comboBox_5.setItemText(17, _translate("promfi_dialog", "r"))
        self.comboBox_5.setItemText(18, _translate("promfi_dialog", "s"))
        self.comboBox_5.setItemText(19, _translate("promfi_dialog", "t"))
        self.comboBox_5.setItemText(20, _translate("promfi_dialog", "u"))
        self.comboBox_5.setItemText(21, _translate("promfi_dialog", "v"))
        self.comboBox_5.setItemText(22, _translate("promfi_dialog", "w"))
        self.comboBox_5.setItemText(23, _translate("promfi_dialog", "x"))
        self.comboBox_5.setItemText(24, _translate("promfi_dialog", "y"))
        self.comboBox_5.setItemText(25, _translate("promfi_dialog", "z"))
        self.comboBox_5.setItemText(26, _translate("promfi_dialog", "A"))
        self.comboBox_5.setItemText(27, _translate("promfi_dialog", "B"))
        self.comboBox_5.setItemText(28, _translate("promfi_dialog", "C"))
        self.comboBox_5.setItemText(29, _translate("promfi_dialog", "D"))
        self.comboBox_5.setItemText(30, _translate("promfi_dialog", "E"))
        self.comboBox_5.setItemText(31, _translate("promfi_dialog", "F"))
        self.comboBox_5.setItemText(32, _translate("promfi_dialog", "G"))
        self.comboBox_5.setItemText(33, _translate("promfi_dialog", "H"))
        self.comboBox_5.setItemText(34, _translate("promfi_dialog", "I"))
        self.comboBox_5.setItemText(35, _translate("promfi_dialog", "J"))
        self.comboBox_5.setItemText(36, _translate("promfi_dialog", "K"))
        self.comboBox_5.setItemText(37, _translate("promfi_dialog", "L"))
        self.comboBox_5.setItemText(38, _translate("promfi_dialog", "M"))
        self.comboBox_5.setItemText(39, _translate("promfi_dialog", "N"))
        self.comboBox_5.setItemText(40, _translate("promfi_dialog", "O"))
        self.comboBox_5.setItemText(41, _translate("promfi_dialog", "P"))
        self.comboBox_5.setItemText(42, _translate("promfi_dialog", "Q"))
        self.comboBox_5.setItemText(43, _translate("promfi_dialog", "R"))
        self.comboBox_5.setItemText(44, _translate("promfi_dialog", "S"))
        self.comboBox_5.setItemText(45, _translate("promfi_dialog", "T"))
        self.comboBox_5.setItemText(46, _translate("promfi_dialog", "U"))
        self.comboBox_5.setItemText(47, _translate("promfi_dialog", "V"))
        self.comboBox_5.setItemText(48, _translate("promfi_dialog", "W"))
        self.comboBox_5.setItemText(49, _translate("promfi_dialog", "X"))
        self.comboBox_5.setItemText(50, _translate("promfi_dialog", "Y"))
        self.comboBox_5.setItemText(51, _translate("promfi_dialog", "Z"))
        self.label_4.setText(_translate("promfi_dialog", "."))
        self.label_2.setText(_translate("promfi_dialog", "."))
        self.comboBox_2.setItemText(0, _translate("promfi_dialog", "a"))
        self.comboBox_2.setItemText(1, _translate("promfi_dialog", "b"))
        self.comboBox_2.setItemText(2, _translate("promfi_dialog", "c"))
        self.comboBox_2.setItemText(3, _translate("promfi_dialog", "d"))
        self.comboBox_2.setItemText(4, _translate("promfi_dialog", "e"))
        self.comboBox_2.setItemText(5, _translate("promfi_dialog", "f"))
        self.comboBox_2.setItemText(6, _translate("promfi_dialog", "g"))
        self.comboBox_2.setItemText(7, _translate("promfi_dialog", "h"))
        self.comboBox_2.setItemText(8, _translate("promfi_dialog", "i"))
        self.comboBox_2.setItemText(9, _translate("promfi_dialog", "j"))
        self.comboBox_2.setItemText(10, _translate("promfi_dialog", "k"))
        self.comboBox_2.setItemText(11, _translate("promfi_dialog", "l"))
        self.comboBox_2.setItemText(12, _translate("promfi_dialog", "m"))
        self.comboBox_2.setItemText(13, _translate("promfi_dialog", "n"))
        self.comboBox_2.setItemText(14, _translate("promfi_dialog", "o"))
        self.comboBox_2.setItemText(15, _translate("promfi_dialog", "p"))
        self.comboBox_2.setItemText(16, _translate("promfi_dialog", "q"))
        self.comboBox_2.setItemText(17, _translate("promfi_dialog", "r"))
        self.comboBox_2.setItemText(18, _translate("promfi_dialog", "s"))
        self.comboBox_2.setItemText(19, _translate("promfi_dialog", "t"))
        self.comboBox_2.setItemText(20, _translate("promfi_dialog", "u"))
        self.comboBox_2.setItemText(21, _translate("promfi_dialog", "v"))
        self.comboBox_2.setItemText(22, _translate("promfi_dialog", "w"))
        self.comboBox_2.setItemText(23, _translate("promfi_dialog", "x"))
        self.comboBox_2.setItemText(24, _translate("promfi_dialog", "y"))
        self.comboBox_2.setItemText(25, _translate("promfi_dialog", "z"))
        self.comboBox_2.setItemText(26, _translate("promfi_dialog", "A"))
        self.comboBox_2.setItemText(27, _translate("promfi_dialog", "B"))
        self.comboBox_2.setItemText(28, _translate("promfi_dialog", "C"))
        self.comboBox_2.setItemText(29, _translate("promfi_dialog", "D"))
        self.comboBox_2.setItemText(30, _translate("promfi_dialog", "E"))
        self.comboBox_2.setItemText(31, _translate("promfi_dialog", "F"))
        self.comboBox_2.setItemText(32, _translate("promfi_dialog", "G"))
        self.comboBox_2.setItemText(33, _translate("promfi_dialog", "H"))
        self.comboBox_2.setItemText(34, _translate("promfi_dialog", "I"))
        self.comboBox_2.setItemText(35, _translate("promfi_dialog", "J"))
        self.comboBox_2.setItemText(36, _translate("promfi_dialog", "K"))
        self.comboBox_2.setItemText(37, _translate("promfi_dialog", "L"))
        self.comboBox_2.setItemText(38, _translate("promfi_dialog", "M"))
        self.comboBox_2.setItemText(39, _translate("promfi_dialog", "N"))
        self.comboBox_2.setItemText(40, _translate("promfi_dialog", "O"))
        self.comboBox_2.setItemText(41, _translate("promfi_dialog", "P"))
        self.comboBox_2.setItemText(42, _translate("promfi_dialog", "Q"))
        self.comboBox_2.setItemText(43, _translate("promfi_dialog", "R"))
        self.comboBox_2.setItemText(44, _translate("promfi_dialog", "S"))
        self.comboBox_2.setItemText(45, _translate("promfi_dialog", "T"))
        self.comboBox_2.setItemText(46, _translate("promfi_dialog", "U"))
        self.comboBox_2.setItemText(47, _translate("promfi_dialog", "V"))
        self.comboBox_2.setItemText(48, _translate("promfi_dialog", "W"))
        self.comboBox_2.setItemText(49, _translate("promfi_dialog", "X"))
        self.comboBox_2.setItemText(50, _translate("promfi_dialog", "Y"))
        self.comboBox_2.setItemText(51, _translate("promfi_dialog", "Z"))
        self.label_3.setText(_translate("promfi_dialog", "."))
        self.comboBox_3.setItemText(0, _translate("promfi_dialog", "a"))
        self.comboBox_3.setItemText(1, _translate("promfi_dialog", "b"))
        self.comboBox_3.setItemText(2, _translate("promfi_dialog", "c"))
        self.comboBox_3.setItemText(3, _translate("promfi_dialog", "d"))
        self.comboBox_3.setItemText(4, _translate("promfi_dialog", "e"))
        self.comboBox_3.setItemText(5, _translate("promfi_dialog", "f"))
        self.comboBox_3.setItemText(6, _translate("promfi_dialog", "g"))
        self.comboBox_3.setItemText(7, _translate("promfi_dialog", "h"))
        self.comboBox_3.setItemText(8, _translate("promfi_dialog", "i"))
        self.comboBox_3.setItemText(9, _translate("promfi_dialog", "j"))
        self.comboBox_3.setItemText(10, _translate("promfi_dialog", "k"))
        self.comboBox_3.setItemText(11, _translate("promfi_dialog", "l"))
        self.comboBox_3.setItemText(12, _translate("promfi_dialog", "m"))
        self.comboBox_3.setItemText(13, _translate("promfi_dialog", "n"))
        self.comboBox_3.setItemText(14, _translate("promfi_dialog", "o"))
        self.comboBox_3.setItemText(15, _translate("promfi_dialog", "p"))
        self.comboBox_3.setItemText(16, _translate("promfi_dialog", "q"))
        self.comboBox_3.setItemText(17, _translate("promfi_dialog", "r"))
        self.comboBox_3.setItemText(18, _translate("promfi_dialog", "s"))
        self.comboBox_3.setItemText(19, _translate("promfi_dialog", "t"))
        self.comboBox_3.setItemText(20, _translate("promfi_dialog", "u"))
        self.comboBox_3.setItemText(21, _translate("promfi_dialog", "v"))
        self.comboBox_3.setItemText(22, _translate("promfi_dialog", "w"))
        self.comboBox_3.setItemText(23, _translate("promfi_dialog", "x"))
        self.comboBox_3.setItemText(24, _translate("promfi_dialog", "y"))
        self.comboBox_3.setItemText(25, _translate("promfi_dialog", "z"))
        self.comboBox_3.setItemText(26, _translate("promfi_dialog", "A"))
        self.comboBox_3.setItemText(27, _translate("promfi_dialog", "B"))
        self.comboBox_3.setItemText(28, _translate("promfi_dialog", "C"))
        self.comboBox_3.setItemText(29, _translate("promfi_dialog", "D"))
        self.comboBox_3.setItemText(30, _translate("promfi_dialog", "E"))
        self.comboBox_3.setItemText(31, _translate("promfi_dialog", "F"))
        self.comboBox_3.setItemText(32, _translate("promfi_dialog", "G"))
        self.comboBox_3.setItemText(33, _translate("promfi_dialog", "H"))
        self.comboBox_3.setItemText(34, _translate("promfi_dialog", "I"))
        self.comboBox_3.setItemText(35, _translate("promfi_dialog", "J"))
        self.comboBox_3.setItemText(36, _translate("promfi_dialog", "K"))
        self.comboBox_3.setItemText(37, _translate("promfi_dialog", "L"))
        self.comboBox_3.setItemText(38, _translate("promfi_dialog", "M"))
        self.comboBox_3.setItemText(39, _translate("promfi_dialog", "N"))
        self.comboBox_3.setItemText(40, _translate("promfi_dialog", "O"))
        self.comboBox_3.setItemText(41, _translate("promfi_dialog", "P"))
        self.comboBox_3.setItemText(42, _translate("promfi_dialog", "Q"))
        self.comboBox_3.setItemText(43, _translate("promfi_dialog", "R"))
        self.comboBox_3.setItemText(44, _translate("promfi_dialog", "S"))
        self.comboBox_3.setItemText(45, _translate("promfi_dialog", "T"))
        self.comboBox_3.setItemText(46, _translate("promfi_dialog", "U"))
        self.comboBox_3.setItemText(47, _translate("promfi_dialog", "V"))
        self.comboBox_3.setItemText(48, _translate("promfi_dialog", "W"))
        self.comboBox_3.setItemText(49, _translate("promfi_dialog", "X"))
        self.comboBox_3.setItemText(50, _translate("promfi_dialog", "Y"))
        self.comboBox_3.setItemText(51, _translate("promfi_dialog", "Z"))
        self.comboBox_4.setItemText(0, _translate("promfi_dialog", "a"))
        self.comboBox_4.setItemText(1, _translate("promfi_dialog", "b"))
        self.comboBox_4.setItemText(2, _translate("promfi_dialog", "c"))
        self.comboBox_4.setItemText(3, _translate("promfi_dialog", "d"))
        self.comboBox_4.setItemText(4, _translate("promfi_dialog", "e"))
        self.comboBox_4.setItemText(5, _translate("promfi_dialog", "f"))
        self.comboBox_4.setItemText(6, _translate("promfi_dialog", "g"))
        self.comboBox_4.setItemText(7, _translate("promfi_dialog", "h"))
        self.comboBox_4.setItemText(8, _translate("promfi_dialog", "i"))
        self.comboBox_4.setItemText(9, _translate("promfi_dialog", "j"))
        self.comboBox_4.setItemText(10, _translate("promfi_dialog", "k"))
        self.comboBox_4.setItemText(11, _translate("promfi_dialog", "l"))
        self.comboBox_4.setItemText(12, _translate("promfi_dialog", "m"))
        self.comboBox_4.setItemText(13, _translate("promfi_dialog", "n"))
        self.comboBox_4.setItemText(14, _translate("promfi_dialog", "o"))
        self.comboBox_4.setItemText(15, _translate("promfi_dialog", "p"))
        self.comboBox_4.setItemText(16, _translate("promfi_dialog", "q"))
        self.comboBox_4.setItemText(17, _translate("promfi_dialog", "r"))
        self.comboBox_4.setItemText(18, _translate("promfi_dialog", "s"))
        self.comboBox_4.setItemText(19, _translate("promfi_dialog", "t"))
        self.comboBox_4.setItemText(20, _translate("promfi_dialog", "u"))
        self.comboBox_4.setItemText(21, _translate("promfi_dialog", "v"))
        self.comboBox_4.setItemText(22, _translate("promfi_dialog", "w"))
        self.comboBox_4.setItemText(23, _translate("promfi_dialog", "x"))
        self.comboBox_4.setItemText(24, _translate("promfi_dialog", "y"))
        self.comboBox_4.setItemText(25, _translate("promfi_dialog", "z"))
        self.comboBox_4.setItemText(26, _translate("promfi_dialog", "A"))
        self.comboBox_4.setItemText(27, _translate("promfi_dialog", "B"))
        self.comboBox_4.setItemText(28, _translate("promfi_dialog", "C"))
        self.comboBox_4.setItemText(29, _translate("promfi_dialog", "D"))
        self.comboBox_4.setItemText(30, _translate("promfi_dialog", "E"))
        self.comboBox_4.setItemText(31, _translate("promfi_dialog", "F"))
        self.comboBox_4.setItemText(32, _translate("promfi_dialog", "G"))
        self.comboBox_4.setItemText(33, _translate("promfi_dialog", "H"))
        self.comboBox_4.setItemText(34, _translate("promfi_dialog", "I"))
        self.comboBox_4.setItemText(35, _translate("promfi_dialog", "J"))
        self.comboBox_4.setItemText(36, _translate("promfi_dialog", "K"))
        self.comboBox_4.setItemText(37, _translate("promfi_dialog", "L"))
        self.comboBox_4.setItemText(38, _translate("promfi_dialog", "M"))
        self.comboBox_4.setItemText(39, _translate("promfi_dialog", "N"))
        self.comboBox_4.setItemText(40, _translate("promfi_dialog", "O"))
        self.comboBox_4.setItemText(41, _translate("promfi_dialog", "P"))
        self.comboBox_4.setItemText(42, _translate("promfi_dialog", "Q"))
        self.comboBox_4.setItemText(43, _translate("promfi_dialog", "R"))
        self.comboBox_4.setItemText(44, _translate("promfi_dialog", "S"))
        self.comboBox_4.setItemText(45, _translate("promfi_dialog", "T"))
        self.comboBox_4.setItemText(46, _translate("promfi_dialog", "U"))
        self.comboBox_4.setItemText(47, _translate("promfi_dialog", "V"))
        self.comboBox_4.setItemText(48, _translate("promfi_dialog", "W"))
        self.comboBox_4.setItemText(49, _translate("promfi_dialog", "X"))
        self.comboBox_4.setItemText(50, _translate("promfi_dialog", "Y"))
        self.comboBox_4.setItemText(51, _translate("promfi_dialog", "Z"))
        self.comboBox.setItemText(0, _translate("promfi_dialog", "a"))
        self.comboBox.setItemText(1, _translate("promfi_dialog", "b"))
        self.comboBox.setItemText(2, _translate("promfi_dialog", "c"))
        self.comboBox.setItemText(3, _translate("promfi_dialog", "d"))
        self.comboBox.setItemText(4, _translate("promfi_dialog", "e"))
        self.comboBox.setItemText(5, _translate("promfi_dialog", "f"))
        self.comboBox.setItemText(6, _translate("promfi_dialog", "g"))
        self.comboBox.setItemText(7, _translate("promfi_dialog", "h"))
        self.comboBox.setItemText(8, _translate("promfi_dialog", "i"))
        self.comboBox.setItemText(9, _translate("promfi_dialog", "j"))
        self.comboBox.setItemText(10, _translate("promfi_dialog", "k"))
        self.comboBox.setItemText(11, _translate("promfi_dialog", "l"))
        self.comboBox.setItemText(12, _translate("promfi_dialog", "m"))
        self.comboBox.setItemText(13, _translate("promfi_dialog", "n"))
        self.comboBox.setItemText(14, _translate("promfi_dialog", "o"))
        self.comboBox.setItemText(15, _translate("promfi_dialog", "p"))
        self.comboBox.setItemText(16, _translate("promfi_dialog", "q"))
        self.comboBox.setItemText(17, _translate("promfi_dialog", "r"))
        self.comboBox.setItemText(18, _translate("promfi_dialog", "s"))
        self.comboBox.setItemText(19, _translate("promfi_dialog", "t"))
        self.comboBox.setItemText(20, _translate("promfi_dialog", "u"))
        self.comboBox.setItemText(21, _translate("promfi_dialog", "v"))
        self.comboBox.setItemText(22, _translate("promfi_dialog", "w"))
        self.comboBox.setItemText(23, _translate("promfi_dialog", "x"))
        self.comboBox.setItemText(24, _translate("promfi_dialog", "y"))
        self.comboBox.setItemText(25, _translate("promfi_dialog", "z"))
        self.comboBox.setItemText(26, _translate("promfi_dialog", "A"))
        self.comboBox.setItemText(27, _translate("promfi_dialog", "B"))
        self.comboBox.setItemText(28, _translate("promfi_dialog", "C"))
        self.comboBox.setItemText(29, _translate("promfi_dialog", "D"))
        self.comboBox.setItemText(30, _translate("promfi_dialog", "E"))
        self.comboBox.setItemText(31, _translate("promfi_dialog", "F"))
        self.comboBox.setItemText(32, _translate("promfi_dialog", "G"))
        self.comboBox.setItemText(33, _translate("promfi_dialog", "H"))
        self.comboBox.setItemText(34, _translate("promfi_dialog", "I"))
        self.comboBox.setItemText(35, _translate("promfi_dialog", "J"))
        self.comboBox.setItemText(36, _translate("promfi_dialog", "K"))
        self.comboBox.setItemText(37, _translate("promfi_dialog", "L"))
        self.comboBox.setItemText(38, _translate("promfi_dialog", "M"))
        self.comboBox.setItemText(39, _translate("promfi_dialog", "N"))
        self.comboBox.setItemText(40, _translate("promfi_dialog", "O"))
        self.comboBox.setItemText(41, _translate("promfi_dialog", "P"))
        self.comboBox.setItemText(42, _translate("promfi_dialog", "Q"))
        self.comboBox.setItemText(43, _translate("promfi_dialog", "R"))
        self.comboBox.setItemText(44, _translate("promfi_dialog", "S"))
        self.comboBox.setItemText(45, _translate("promfi_dialog", "T"))
        self.comboBox.setItemText(46, _translate("promfi_dialog", "U"))
        self.comboBox.setItemText(47, _translate("promfi_dialog", "V"))
        self.comboBox.setItemText(48, _translate("promfi_dialog", "W"))
        self.comboBox.setItemText(49, _translate("promfi_dialog", "X"))
        self.comboBox.setItemText(50, _translate("promfi_dialog", "Y"))
        self.comboBox.setItemText(51, _translate("promfi_dialog", "Z"))
        self.groupBox_3.setTitle(_translate("promfi_dialog", "Task Code"))
        self.comboBox_9.setItemText(0, _translate("promfi_dialog", "A"))
        self.comboBox_9.setItemText(1, _translate("promfi_dialog", "B"))
        self.comboBox_9.setItemText(2, _translate("promfi_dialog", "C"))
        self.comboBox_9.setItemText(3, _translate("promfi_dialog", "D"))
        self.comboBox_9.setItemText(4, _translate("promfi_dialog", "E"))
        self.comboBox_9.setItemText(5, _translate("promfi_dialog", "F"))
        self.comboBox_9.setItemText(6, _translate("promfi_dialog", "G"))
        self.comboBox_9.setItemText(7, _translate("promfi_dialog", "H"))
        self.comboBox_9.setItemText(8, _translate("promfi_dialog", "I"))
        self.comboBox_9.setItemText(9, _translate("promfi_dialog", "J"))
        self.comboBox_9.setItemText(10, _translate("promfi_dialog", "K"))
        self.comboBox_9.setItemText(11, _translate("promfi_dialog", "L"))
        self.comboBox_9.setItemText(12, _translate("promfi_dialog", "M"))
        self.comboBox_9.setItemText(13, _translate("promfi_dialog", "N"))
        self.comboBox_9.setItemText(14, _translate("promfi_dialog", "O"))
        self.comboBox_9.setItemText(15, _translate("promfi_dialog", "P"))
        self.comboBox_9.setItemText(16, _translate("promfi_dialog", "Q"))
        self.comboBox_9.setItemText(17, _translate("promfi_dialog", "R"))
        self.comboBox_9.setItemText(18, _translate("promfi_dialog", "S"))
        self.comboBox_9.setItemText(19, _translate("promfi_dialog", "T"))
        self.comboBox_9.setItemText(20, _translate("promfi_dialog", "U"))
        self.comboBox_9.setItemText(21, _translate("promfi_dialog", "V"))
        self.comboBox_9.setItemText(22, _translate("promfi_dialog", "W"))
        self.comboBox_9.setItemText(23, _translate("promfi_dialog", "X"))
        self.comboBox_9.setItemText(24, _translate("promfi_dialog", "Y"))
        self.comboBox_9.setItemText(25, _translate("promfi_dialog", "Z"))
        self.label_7.setText(_translate("promfi_dialog", "-"))
        self.comboBox_12.setItemText(0, _translate("promfi_dialog", "A"))
        self.comboBox_12.setItemText(1, _translate("promfi_dialog", "B"))
        self.comboBox_12.setItemText(2, _translate("promfi_dialog", "C"))
        self.comboBox_12.setItemText(3, _translate("promfi_dialog", "D"))
        self.comboBox_12.setItemText(4, _translate("promfi_dialog", "E"))
        self.comboBox_12.setItemText(5, _translate("promfi_dialog", "F"))
        self.comboBox_12.setItemText(6, _translate("promfi_dialog", "G"))
        self.comboBox_12.setItemText(7, _translate("promfi_dialog", "H"))
        self.comboBox_12.setItemText(8, _translate("promfi_dialog", "I"))
        self.comboBox_12.setItemText(9, _translate("promfi_dialog", "J"))
        self.comboBox_12.setItemText(10, _translate("promfi_dialog", "K"))
        self.comboBox_12.setItemText(11, _translate("promfi_dialog", "L"))
        self.comboBox_12.setItemText(12, _translate("promfi_dialog", "M"))
        self.comboBox_12.setItemText(13, _translate("promfi_dialog", "N"))
        self.comboBox_12.setItemText(14, _translate("promfi_dialog", "O"))
        self.comboBox_12.setItemText(15, _translate("promfi_dialog", "P"))
        self.comboBox_12.setItemText(16, _translate("promfi_dialog", "Q"))
        self.comboBox_12.setItemText(17, _translate("promfi_dialog", "R"))
        self.comboBox_12.setItemText(18, _translate("promfi_dialog", "S"))
        self.comboBox_12.setItemText(19, _translate("promfi_dialog", "T"))
        self.comboBox_12.setItemText(20, _translate("promfi_dialog", "U"))
        self.comboBox_12.setItemText(21, _translate("promfi_dialog", "V"))
        self.comboBox_12.setItemText(22, _translate("promfi_dialog", "W"))
        self.comboBox_12.setItemText(23, _translate("promfi_dialog", "X"))
        self.comboBox_12.setItemText(24, _translate("promfi_dialog", "Y"))
        self.comboBox_12.setItemText(25, _translate("promfi_dialog", "Z"))
        self.comboBox_10.setItemText(0, _translate("promfi_dialog", "A"))
        self.comboBox_10.setItemText(1, _translate("promfi_dialog", "B"))
        self.comboBox_10.setItemText(2, _translate("promfi_dialog", "C"))
        self.comboBox_10.setItemText(3, _translate("promfi_dialog", "D"))
        self.comboBox_10.setItemText(4, _translate("promfi_dialog", "E"))
        self.comboBox_10.setItemText(5, _translate("promfi_dialog", "F"))
        self.comboBox_10.setItemText(6, _translate("promfi_dialog", "G"))
        self.comboBox_10.setItemText(7, _translate("promfi_dialog", "H"))
        self.comboBox_10.setItemText(8, _translate("promfi_dialog", "I"))
        self.comboBox_10.setItemText(9, _translate("promfi_dialog", "J"))
        self.comboBox_10.setItemText(10, _translate("promfi_dialog", "K"))
        self.comboBox_10.setItemText(11, _translate("promfi_dialog", "L"))
        self.comboBox_10.setItemText(12, _translate("promfi_dialog", "M"))
        self.comboBox_10.setItemText(13, _translate("promfi_dialog", "N"))
        self.comboBox_10.setItemText(14, _translate("promfi_dialog", "O"))
        self.comboBox_10.setItemText(15, _translate("promfi_dialog", "P"))
        self.comboBox_10.setItemText(16, _translate("promfi_dialog", "Q"))
        self.comboBox_10.setItemText(17, _translate("promfi_dialog", "R"))
        self.comboBox_10.setItemText(18, _translate("promfi_dialog", "S"))
        self.comboBox_10.setItemText(19, _translate("promfi_dialog", "T"))
        self.comboBox_10.setItemText(20, _translate("promfi_dialog", "U"))
        self.comboBox_10.setItemText(21, _translate("promfi_dialog", "V"))
        self.comboBox_10.setItemText(22, _translate("promfi_dialog", "W"))
        self.comboBox_10.setItemText(23, _translate("promfi_dialog", "X"))
        self.comboBox_10.setItemText(24, _translate("promfi_dialog", "Y"))
        self.comboBox_10.setItemText(25, _translate("promfi_dialog", "Z"))
        self.comboBox_13.setItemText(0, _translate("promfi_dialog", "A"))
        self.comboBox_13.setItemText(1, _translate("promfi_dialog", "B"))
        self.comboBox_13.setItemText(2, _translate("promfi_dialog", "C"))
        self.comboBox_13.setItemText(3, _translate("promfi_dialog", "D"))
        self.comboBox_13.setItemText(4, _translate("promfi_dialog", "E"))
        self.comboBox_13.setItemText(5, _translate("promfi_dialog", "F"))
        self.comboBox_13.setItemText(6, _translate("promfi_dialog", "G"))
        self.comboBox_13.setItemText(7, _translate("promfi_dialog", "H"))
        self.comboBox_13.setItemText(8, _translate("promfi_dialog", "I"))
        self.comboBox_13.setItemText(9, _translate("promfi_dialog", "J"))
        self.comboBox_13.setItemText(10, _translate("promfi_dialog", "K"))
        self.comboBox_13.setItemText(11, _translate("promfi_dialog", "L"))
        self.comboBox_13.setItemText(12, _translate("promfi_dialog", "M"))
        self.comboBox_13.setItemText(13, _translate("promfi_dialog", "N"))
        self.comboBox_13.setItemText(14, _translate("promfi_dialog", "O"))
        self.comboBox_13.setItemText(15, _translate("promfi_dialog", "P"))
        self.comboBox_13.setItemText(16, _translate("promfi_dialog", "Q"))
        self.comboBox_13.setItemText(17, _translate("promfi_dialog", "R"))
        self.comboBox_13.setItemText(18, _translate("promfi_dialog", "S"))
        self.comboBox_13.setItemText(19, _translate("promfi_dialog", "T"))
        self.comboBox_13.setItemText(20, _translate("promfi_dialog", "U"))
        self.comboBox_13.setItemText(21, _translate("promfi_dialog", "V"))
        self.comboBox_13.setItemText(22, _translate("promfi_dialog", "W"))
        self.comboBox_13.setItemText(23, _translate("promfi_dialog", "X"))
        self.comboBox_13.setItemText(24, _translate("promfi_dialog", "Y"))
        self.comboBox_13.setItemText(25, _translate("promfi_dialog", "Z"))
        self.label_8.setText(_translate("promfi_dialog", "_"))
        self.pushButton.setText(_translate("promfi_dialog", "Generate"))
        self.pushButton_3.setText(_translate("promfi_dialog", "TESTAAA"))
        # self.pushButton_2.setText(_translate("promfi_dialog", "Store"))


    # def print_message(self):
    #     print("Hello World")



# class Test_aa(object):
#     def __init__(self):
#         super(Test_aa, self).__init__()
#         loadUi('Promfi 2.0.ui', self)
#         self.pushbutton.clicked.connect(self.retrieveText)


    # def retrieveText(self):
    #     words = self.comboBox_10.toPlainText()
    #     self.textEdit.setText(words)


    def takeText(self):
        # Project Number Selector
        aa = self.comboBox_14.currentText() # 67589
        ab = self.comboBox_15.currentText()
        ac = self.comboBox_16.currentText()
        ad = self.comboBox_17.currentText()
        ae = self.comboBox_18.currentText()
        af = aa + ab + ac + ad + ae
        # Resource Number Selector
        ba = self.comboBox_19.currentText() # 67589
        bb = self.comboBox_20.currentText()
        bc = self.comboBox_21.currentText()
        bd = self.comboBox_22.currentText()
        be = ba + bb + bc + bd
        # Task Code Selector
        ca = self.comboBox_12.currentText()
        cb = self.comboBox_9.currentText()
        cc = self.comboBox_13.currentText()
        cd = self.comboBox_10.currentText()
        ce = ca + cb + "-" + cc + cd
        # Relationship Code Selector
        da = self.comboBox.currentText()
        db = self.comboBox_2.currentText()
        dc = self.comboBox_3.currentText()
        dd = self.comboBox_4.currentText()
        de = self.comboBox_5.currentText()
        df = self.comboBox_6.currentText()
        de = da + db + dc + "." + dd + "." + de + "." + df
        # sequence combinator
        combined_sequence = af + "-" + be + "_" + ce + de
        # combined_sequence_2 = af + "-" + be + "_" + ce + de + "OLEX"
        self.textEdit.setText(combined_sequence)
        # self.textEdit.setText(combined_sequence_2)


    # def testAAA(self):
    # #     os.chdir('F:/00223-PROMFI DATABASE SYSTEM MANAGER/3.5.1 - 00223-PZ-PZ PROMFI SYSTEM')
    #     os.chdir('C:/Users/Ziloeh/Google Drive(jfcollege00 @ gmail.com)/Others')
    #     projects_workbook = xl.load_workbook('book1.xlsx')
    # #     projects_workbook = xl.load_workbook('PROMFI 1.4.xlsx', data_only=True)
    # #     tasks_sheet = projects_workbook['TAP.P']
    #     tasks_sheet = projects_workbook['sheet1']
    # #     # guess1 = input('guess a family task code: ')
    # #     # guess2 = input('guess a parent task code: ')
    #     task_code_selection = tasks_sheet.cell(4, 2)
    # #     # print(task_code_selection)
    # #     testAAA_var = "x"
    #
    #     self.textEdit.setText(task_code_selection)


    # def task_code(self):
    #     os.chdir('F:/00223-PROMFI DATABASE SYSTEM MANAGER/3.5.1 - 00223-PZ-PZ PROMFI SYSTEM')
    #     projects_workbook = xl.load_workbook('PROMFI 1.4.xlsx', data_only=True)
    #     tasks_sheet = projects_workbook['TAP.P']
    #     guess1 = input('guess a family task code: ')
    #     guess2 = input('guess a parent task code: ')
    #     print(f"Task Code Options are: ")
    #     for row in range(16, tasks_sheet.max_row + 1):
    #         task_code_selection = tasks_sheet.cell(row, 3)
    #         family_task_code = tasks_sheet.cell(row, 4)
    #         family_task_description = tasks_sheet.cell(row, 5)
    #         parent_task_code = tasks_sheet.cell(row, 6)
    #         parent_task_description = tasks_sheet.cell(row, 7)
    #         child_task_code = tasks_sheet.cell(row, 8)
    #         child_task_description = tasks_sheet.cell(row, 9)
    #         task_options_list = {
    #             task_code_selection.value: family_task_code.value,
    #             task_code_selection.value: family_task_description.value,
    #             task_code_selection.value: parent_task_code.value,
    #             task_code_selection.value: parent_task_description.value,
    #             task_code_selection.value: child_task_code.value,
    #             task_code_selection.value: child_task_description.value
    #         }
    #         if guess1 == family_task_code.value and guess2 == parent_task_code.value:
    #             #  and guess3 == child_task_description.value
    #             print(f"{task_options_list}")  # , end=" "
    #         self.textEdit.setText(task_options_list)


    def soflo(self):
        sumMofo = "x"
        self.textEdit.setText(sumMofo)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    promfi_dialog = QtWidgets.QDialog()
    ui = Ui_promfi_dialog()
    ui.setupUi(promfi_dialog)
    promfi_dialog.show()
    sys.exit(app.exec_())

